%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\adria\OneDrive\Desktop\Projects\Shutter\shutter_processing\dist_50cm (1).csv
%
% Auto-generated by MATLAB on 10-Aug-2022 15:38:57

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["idx", "t_ms", "v", "test_type", "dist_cm", "lux", "ang_deg", "panel", "shutter_n", "n_samples"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["test_type", "dist_cm", "lux", "ang_deg", "panel", "shutter_n", "n_samples"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["test_type", "dist_cm", "lux", "ang_deg", "panel", "shutter_n", "n_samples"], "ThousandsSeparator", ",");

% Import the data
i=1;
for file = dir("*.csv")'
    distance_signals{i} = readtable(file.name, opts);
    i=i+1;
end

save("distance_signal_data_mancheseter.mat", "distance_signals");

%% Clear temporary variables
clear opts